feat: task7, add views, add test controller
DenisTDA/TestGuru pull request #11
Opened 2022-03-13 12:06 UTC by DenisTDA

2022-03-13 17:59 UTC, VidgarVii requested changes

2022-03-13 17:59 UTC, VidgarVii commented on app/assets/stylesheets/application.css
> + }
тут сильно не хватает отступов. используй соглашение стайл гайда 
https://google.github.io/styleguide/htmlcssguide.html

2022-03-13 17:59 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    def index
важно:
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2022-03-13 17:59 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.find(params[:id])
у тебя уже есть вопрос

2022-03-13 17:59 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +  end
не стоит полагаться на глобальное состояние (инстанс-переменные) в хелпере
лучше передавать вопрос параметром, иначе потом не разберешь откуда эти данные тут взялись
так же легко забыть, что здесь используется эта инстанс-переменная, переименовать ее при рефакторинге и сломать код

2022-03-13 17:59 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +    Date::DATE_FORMATS[:year] = '%Y'
не надо изменять глобальное состояние. Завтра ты забудешь про это. И запрашиваю год и не поймешь почему результат не ожидаемый.
Метод должен просто вернуть тущий год. Без сайд эффектов!

2022-03-13 17:59 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +    (link_to "#{author}, #{repo}", 'https://github.com/DenisTDA/TestGuru', rel: 'nofollow' 'noopener', target: '_blank' )
скобки тут какую роль играют?

2022-03-13 17:59 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +  <%= render 'shared/errors', resurce: @test%>
что нам даёт показ ошибок теста? При создании вопроса работает только валидация вопроса

2022-03-13 17:59 UTC, VidgarVii commented on app/views/questions/show.html.erb
> +<p> <%= @question.inspect %> </p>
можно расписать страницу более красочно без использования inspect

2022-03-14 04:54 UTC, DenisTDA commented on app/controllers/questions_controller.rb
>    def index
Из текста задания не вытекает необходимый результат. Если абстрагироваться от ужебного процесса, то моя реализация тоже выводит на одной странице Тест и список к нему вопросов. Как задание понял, так и сделал.

2022-03-14 04:54 UTC, DenisTDA commented on app/controllers/questions_controller.rb
>    def index
теперь ЦЕЛЬ ясна.

2022-03-14 05:02 UTC, DenisTDA commented on app/helpers/questions_helper.rb
> +  end
поправил

2022-03-14 05:03 UTC, DenisTDA commented on app/assets/stylesheets/application.css
> + }
исправил

2022-03-14 05:05 UTC, DenisTDA commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.find(params[:id])
мая невнимательность. поправил.

2022-03-14 05:17 UTC, DenisTDA commented on app/helpers/questions_helper.rb
> +    Date::DATE_FORMATS[:year] = '%Y'
исправил

2022-03-14 05:18 UTC, DenisTDA commented on app/helpers/questions_helper.rb
> +    (link_to "#{author}, #{repo}", 'https://github.com/DenisTDA/TestGuru', rel: 'nofollow' 'noopener', target: '_blank' )
видимо, роль мусора. поправил.

2022-03-14 05:21 UTC, DenisTDA commented on app/views/questions/new.html.erb
> +  <%= render 'shared/errors', resurce: @test%>
убрал

2022-03-15 06:54 UTC, VidgarVii requested changes

2022-03-15 06:54 UTC, VidgarVii commented on app/assets/stylesheets/application.css
> +
не исправил. 
```css
.content {
  padding-bottom: 90px;
}
```

2022-03-15 06:54 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to test_questions_path(@test)
согласно REST API после создания/обновления ресурса принято показать этот ресурс. Тут конечно не API но будет полезно повторить это соглашение. Так же удобно будет убедиться, что обновление вопроса прошло успешно

2022-03-15 06:54 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +    header.insert(0,"Edit") if params[:action] == 'edit'
тут опять имеется связь (зависимость) с теми данными, которые могут и не быть. Т.е. метод будет работать корректно, только кода звёзды сложатся*
Выше уже писал. Что работать надо с данными которые приходят аргументов в метод. Ни когда не надо зависеть или надеяться от внешнего состояния программы.
Передавай сюда вопрос и спрашивай у него персистентный он или нет
Есть для этого методы `.persisted?` или `.new_record?`

2022-03-15 06:54 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +  end
переменные которые не используется стоит удалить
Они увеличивают потребление памяти

2022-03-15 06:54 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +
для шапок таблицы есть теги thead, th

https://sdelaemblog.ru/html-tegi-thead-th-tbody-tfoot

2022-03-15 06:54 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +    <td align='right' width='20'>| <%= link_to "Delete", test_path(test), method: 'delete', data: {confirm: 'Are you shure?'} %> </td>
стили принято писать и хранить в css файлах. ЧТобы всё было в 1 месте. Так же эти файлы кешируются, что увеличивает время загрузки страницы. А html надо читать и парсить каждый раз

2022-03-15 06:54 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +    <td align='right' width='20'>| <%= link_to "Delete", test_path(test), method: 'delete', data: {confirm: 'Are you shure?'} %> </td>
`{ confirm: 'Are you shure?' }`
следи за отступами

2022-03-15 15:51 UTC, VidgarVii requested changes

2022-03-15 15:51 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    flash[:notice] = "Question '#{@question.body}' was deleted"
лучше если redirect_to будет последней строчкой в экшене.
С начала выполняем все нужные действия с данными. Потом отправляем юзера на страницу, а не на оборот

2022-03-15 15:51 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +      flash[:notice] = "Test '#{@test.title}' was saved successfully"
тоже самое про редирект

2022-03-15 15:51 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to test_questions_path(@test)
не исправил

2022-03-15 15:51 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +  end
прочти внимательно задание. тут всё перепутал

2022-03-15 15:51 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +  <% end %>
лучше не загрязнять макет лишним хтмл кодом. Создай отдельный паршл для флеша и подключи там где он нужен

2022-03-15 15:51 UTC, VidgarVii commented on app/views/questions/edit.html.erb
> +<%= form_with model: @question, local: true do |form| %>
форма для вопроса при создании и обновлении одна и та же. У тебя сейчас просто дублирование кода. Если придётся изменять форму, то придётся делать это в 2х местах. Тут надо отDRYить код

2022-03-15 15:51 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +  <% @tests.each do |test| %>
для коллекций обычно используют render collection
http://rusrails.ru/layouts-and-rendering-in-rails#rendering-kollektsiy

```ruby
  render @tests
```

- Это разгрузит данный файл
- Наведет порядок. Вся работа с нужными ресурсами будет вестись в своеё папке
- Позволит удобней кешировать куски страницы

2022-03-15 15:51 UTC, VidgarVii commented on app/views/tests/show.html.erb
> +<% @test.questions.each do |question|%>
тоже самое про коллекции

2022-03-15 15:55 UTC, DenisTDA commented on app/controllers/questions_controller.rb
> +    flash[:notice] = "Question '#{@question.body}' was deleted"
Честно говоря, думал что сначала выполняется действие, а flash как подтверждение того, что все прошло успешно. Ок.

2022-03-15 16:00 UTC, DenisTDA commented on app/views/tests/index.html.erb
> +  <% @tests.each do |test| %>
Логика была такой: если мы создаем вопрос в рамках теста, то было бы логичнее показать созданный или обнавленный вопрос в составе опять же этого теста. Но раз принято, то ок.

2022-03-16 07:36 UTC, VidgarVii requested changes

2022-03-16 07:36 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      flash[:notice] = "Question '#{@question.body}' was saved successfully"
не исправил

2022-03-16 07:36 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +      flash[:notice] = "Test '#{@test.title}' was saved successfully"
не исправил

2022-03-16 07:36 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +  end
тут передавать тест нет смысла. Текущий тест можно вытащить у вопроса, так как при порождении вопроса тест должен быть

2022-03-16 07:36 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +    header.insert(0, 'Edit') if question.persisted?
не вижу смысла 2 раза проверять объект. Если он new_record то он точно не будет persisted
тут достаточно 1 условного оператора

2022-03-16 07:36 UTC, VidgarVii commented on app/views/questions/_form.html.erb
> +<%= form_with(model: path, local: true ) do |form| %>
просто пишешь `form_with model: [@test, @question]`
для эдит переменная `@test` будет пустая (т.к. при использовании опции "шеллоу тру" в роутах для эдит `@test` не нужен)
соответсвенно в `@test` будет "нил" и рельсы построят правильный путь, потому что придет только `@question`
для нью придут оба объекта ("тест" и "квесшен") и рельсы также построят правильный путь

2022-03-16 07:53 UTC, DenisTDA commented on app/views/questions/_form.html.erb
> +<%= form_with(model: path, local: true ) do |form| %>
нигде этого в документации не видел. А догадываться сложно, когда не знаешь.

2022-03-16 08:10 UTC, DenisTDA commented on app/views/questions/_form.html.erb
> +<%= form_with(model: path, local: true ) do |form| %>
и у меня так на edit не работает..

2022-03-16 14:57 UTC, merged