Task8
DenisTDA/TestGuru pull request #12
Opened 2022-03-19 17:26 UTC by DenisTDA

2022-03-20 08:37 UTC, VidgarVii requested changes

2022-03-20 08:37 UTC, VidgarVii commented on app/controllers/results_controller.rb
> +
лишний отступ

2022-03-20 08:37 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :set_user, only: %i[start]
Для 1 экшена колбек не объявляют, усложняет код. Колбеки это тот еще антипаттерн

2022-03-20 08:37 UTC, VidgarVii commented on app/helpers/results_helper.rb
> +    if result.percentage_result <= 85
вот эта операция сравнения - это по сути бизнес-логика о которой вьюхе знать не надо и ее правильно будет поместить в модель, а здесь оставить что-то типа:

```html
  <% if result.successful? %>
```

2022-03-20 08:37 UTC, VidgarVii commented on app/models/result.rb
> +  before_update :before_update_set_next_question
эти два коллбека делают одно и то же по сути
оба устанавливают следующий вопрос
разница лишь в том, что считать следующим вопросом, т.е разница в поиске этого следующего вопроса

(и обрати внимание - оба вызываются с дополнительным условием, на создании или на апдейте)

имеет смысл объединить их в один простой коллбек:

```ruby
before_validation :set_current_question

...

def set_current_question
  self.current_question = next_question
end
```
а всю различающуюся логику поместить уже в метод `next_question`

(коллбеки бывает удобно использовать, но они часто усложняют код и его отладку, если есть возможность не плодить лишние, то ей надо воспользоваться)


вообще с коллбеками нужно осторожно - они не всегда делают то что ты ожидаешь, тогда когда ты ожидаешь ))
бывают ньюансы о которых не догадываешься, особенно при совместной работе нескольких коллбеков и использовании коллбеков с условиями
поэтому если есть возможность упростить коллбеки, то это нужно делать

2022-03-20 08:37 UTC, VidgarVii commented on app/models/result.rb
> +  end
если answer_ids будет нил, то метод correct_answer? вернёт нил. А это нарушение соглашения предикатных методов. Такие методы должны возвращать только true или false
Это можно сделать без проверки answer_ids. Более декларативном способом

2022-03-20 08:37 UTC, VidgarVii commented on app/models/result.rb
> +
таких вещей уже не должно быть

2022-03-20 12:56 UTC, DenisTDA commented on app/models/result.rb
> +
Не очень понял какое замечание? пустая строка в конце файла..

2022-03-20 13:16 UTC, DenisTDA commented on app/controllers/tests_controller.rb
> +  before_action :set_user, only: %i[start]
Вот над этим долго думал, что ты имел ввиду.. попил чай, прочитал еще раз и наконец дошло, что не надо использовать колбек, если вызов метода только в одном экшене..  :)))))

2022-03-21 06:30 UTC, VidgarVii requested changes

2022-03-21 06:30 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +  before_action :set_answer, only: %i[ show edit update destroy ]
%i[show edit update destroy]

2022-03-21 06:30 UTC, VidgarVii commented on app/models/result.rb
> +    self.percentage_result > 85
лучше "магические цифры" хранить в константах с "говорящими именами"
например `SUCCESS_RATIO`

2022-03-21 06:30 UTC, VidgarVii commented on app/views/answers/_answer.html.erb
> +  </li>
не исправил

2022-03-21 06:30 UTC, VidgarVii commented on app/views/tests/edit.html.erb
> +<%= render 'nav' %>
не исправил

2022-03-21 06:30 UTC, VidgarVii commented on app/views/tests/new.html.erb
> +<%= link_to "List tests", tests_path %>
не исправил

2022-03-22 05:29 UTC, merged