Task13
DenisTDA/TestGuru pull request #17
Opened 2022-04-12 11:09 UTC by DenisTDA

2022-04-13 06:26 UTC, VidgarVii requested changes

2022-04-13 06:26 UTC, VidgarVii commented on Gemfile
> +gem 'dotenv-rails', groups: %i[development test]
есть открытая группа development test
можно туда положить гем

2022-04-13 06:26 UTC, VidgarVii commented on app/controllers/results_controller.rb
> +  end
Gist это модель. Значит согласно rails way для создания ресурса  и записи в БД объекта Gist должен быть отдельный контроллер с экшеном create

2022-04-13 06:26 UTC, VidgarVii commented on app/controllers/results_controller.rb
> +    flash_options = if result_gist
тут проверяется только наличие какого-то результата, а не его успешность или корректность.
result может содержать цифру 1. И при этом будет попытка записи гиста в бд

есть стандартный принятый подход для сервисов

if result.success?

2022-04-13 06:26 UTC, VidgarVii commented on app/controllers/results_controller.rb
> +                      # byebug
отладочный код не должен попадать в репозиторий

2022-04-13 06:26 UTC, VidgarVii commented on app/controllers/results_controller.rb
> +    Gist.create!(html_url: gist[:html_url], question_id: question.id, user_id: user.id)
етод call должен вернуть такой объект, который содержит все нужные методы и данные. И хорошо если всё это будет прописано в явном виде. Сейчас же не понятно от куда берутся методы такие как html_url. 
Для создания такого объекта можно воспользоваться Struct

2022-04-13 06:26 UTC, VidgarVii commented on app/controllers/results_controller.rb
> +  def save_gist(question, user, gist)
create! может остановить дальнейшее выполнение программы. Об этом явно указывает восклицательный знак. В таком случаи метод стоит назвать save_gist!

2022-04-13 06:26 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
установка "нил" в аргументах - это возможно не лучшее решение
я бы для такого случая порекомендовал вариант установки дефолта, к примеру, такой:
```ruby
def initialize(question, client = default_client)
  ...
  @client = client
end
```
далее можно определить в методе `default_client` "дефолтного клиента"

```ruby
private

def default_client
  Octokit::Client.new(access_token: GITHUB_GIST_TOKEN)
end
``

2022-04-13 06:26 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
еще можно так:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```
уменьшит потребление памяти и выглядит лучше

2022-04-13 06:26 UTC, VidgarVii commented on lib/clients/git_hub_client.rb
> +  ACCESS_TOKEN = ENV['ACCESS_TOKEN_TESTGURU']
если ACCESS_TOKEN не будет. то ошибка будет на стороне октокит. Что не совсем корректно. Тем более ты эту ошибку зачем-то обрабатываешь. Лучше проверку токена делать явной. Для этого можно воспользоваться 
ENV.fetch('ACCESS_TOKEN')

2022-04-13 06:26 UTC, VidgarVii commented on lib/clients/git_hub_client.rb
> +  ACCESS_TOKEN = ENV['ACCESS_TOKEN_TESTGURU']
Плохое название для токена. В проектах таких токенов мб сотни. Лучше явно прописывать за что отвечает ключ. Предлагаю для примера GITHUB_ACCESS_TOKEN

2022-04-13 06:26 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    @client = client || GitHubClient.new
Гитхаб клиентов является Октокит. А обёрткой гема будет GistQuestionService. (Кстати не самое лучше название) Создавать GitHubClient нет особого смысла

2022-04-13 06:28 UTC, VidgarVii requested changes

2022-04-13 06:28 UTC, VidgarVii commented on .gitignore
> +.env
в репозитории надо оставить файл .env.example
который будет содержать пустые ENV

2022-04-15 15:46 UTC, VidgarVii requested changes

2022-04-15 15:46 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +  end
у тебя сейчас логика размазана м/у сервисом и контроллером. Сильная логическая связь м/у контроллером и сервисом. Т.е. ты просто часть задачи возложил на контроллер. Это плохо. 
Контроллер просто делегат. Сам он ни чего не делает. Он только знает кого надо дёргать, чтобы выполнилось какая-то задача.
У тебя есть сервис GistQuestionService который создаёт гист. Вот у него или его объектов спрашивай создался гист или нет

2022-04-15 15:46 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +  end
только админ может видеть все созданные гисты

2022-04-15 15:46 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    flash_options = if success?(result_gist) && gist.save
`gist.save!`
так как тут не проверяем входящие параметры при создания объекта то лучше воспользоваться bang! методом. Чтобы точно знать что код работает и Gist в базе создаётся

2022-04-15 15:46 UTC, VidgarVii commented on app/controllers/results_controller.rb
> +  before_action :set_result, only: %i[show result update gist]
лишние артефакты

2022-04-15 15:46 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  GITHUB_GIST_TOKEN = ENV['ACCESS_TOKEN_TESTGURU']
если ACCESS_TOKEN_TESTGURU не будет. то ошибка будет на стороне октокит. Что не совсем корректно. Тем более ты эту ошибку зачем-то обрабатываешь. Лучше проверку токена делать явной. Для этого можно воспользоваться 
ENV.fetch('ACCESS_TOKEN_TESTGURU')

2022-04-15 15:46 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  GITHUB_GIST_TOKEN = ENV['ACCESS_TOKEN_TESTGURU']
ACCESS_TOKEN_TESTGURU так же не говорящее название для токена.
Можно подумать что это токен для доступа к приложению TESTGURU

2022-04-15 15:46 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    Octokit::Client.new(access_token: GITHUB_GIST_TOKEN) if ENV.fetch('ACCESS_TOKEN_TESTGURU')
константа GITHUB_GIST_TOKEN и эта проверка лишняя. fetch выкенет ошибку KeyError
лучше просто написать 

Octokit::Client.new(access_token: ENV.fetch('GITHUB_GIST_TOKEN'))

2022-04-15 15:46 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +                      { notice: t('.success', url_gist: result_gist[:html_url]) }
не решена проблема просачивания методов гема в контроллер.
Если гем поменяется, то придётся исправлять код в не скольких классах. А хотелось бы только в 1. В GistQuestionService

2022-04-16 17:23 UTC, VidgarVii requested changes

2022-04-16 17:23 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +  before_action :require_admin, only: %i[index]
подход с колбеком порождает бардак в коде. И колбеки всегда плохо читаются.
Так же нарушение правила, о котором я говорил ранее. Для 1 экшена колбек не объявляют.

Все экшены админа определяются в папке admins

2022-04-16 17:23 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
хорошо бы передавать полноценный объект. Например гем тебе как раз передают объект Sawyer::Resource. Ты можешь сделать для него адаптер и передавать только нужные данные. Данные у тебя уже есть. А вот объект Hash отдавать попахивает костылём. Сделай класс или [струткуру] (https://ruby-doc.org/core-2.7.0/Struct.html) прям в этом же классе. И отдавай экземпляр этого класса. Только назови его понятно. GistResult например. И тогда будет всё чисто

2022-04-16 17:23 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    { gist: gist,
1 тут может появиться лишняя связь с Sawyer::Resource
2 не вижу чтобы этот ключ использовался. Получается нет смысла его отадать

2022-04-16 17:23 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +      url: gist.url,
отдаёшь не верную ссылку
https://docs.github.com/en/rest/reference/gists#create-a-gist

2022-04-16 17:23 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    gist.url.include?(API_ENDPOINT)
я думаю если ссылка есть, то это уже хороший результат
и тут проверяется не верная ссылка.  Отписал выше

2022-04-16 17:23 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    flash_options = if result_gist[:success?] && gist.save!
gist.save! ставить в условие нет ни какого смысла. Если гист на запишется в базу то будет 500 ошибка.
Я тебе очень прошу. Перепроверяй код который пишешь. Уж больно очень много ошибок

2022-04-16 17:23 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    flash_options = if result_gist[:success?] && gist.save!
`result_gist[:success?]`
а чем стандартный подход, который я предложил ранее плох?
`result_gist.success?`

2022-04-16 17:23 UTC, VidgarVii commented on config/locales/en.yml
> +      success: "Gist was saved successful! The URL: %{url_gist}"
ссылка должна быть кликабельной

2022-04-16 17:23 UTC, VidgarVii commented on app/views/results/show.html.erb
> +  <p><%= link_to  "Gist Question", "/gists?user=#{current_user.id}&result=#{@result.id}", method: :post %></p>
1 current_user можно получить в контроллере
2 передавать параметры в ПОСТ запросе лучше через тело запроса. Параметрами в урл тоже конечно можно. Но зачем усложнять ссылку не совсем понятно.
3 для ссылок используй методы хелперы. Они же удобней чем строить эти строки.

2022-04-16 17:53 UTC, DenisTDA commented on app/controllers/gists_controller.rb
> +    flash_options = if result_gist[:success?] && gist.save!
Смотря что считать ошибками. В целом, для меня большое достижение, что код вообще работает, т.к. я программирую с 17 января 2022 года. Многие вещи еще в голове не уложились, бессистемный поиск решений того или иного вопроса порядка в голове не добавляет. Ты думаешь, мне самому нравиться 10 раз переделывать одно и тоже? Я согласен, что некоторые решения - это костыль, потому как другого решения пока не нашел. Стараюсь, на сколько хватает головы.

2022-04-16 18:02 UTC, DenisTDA commented on app/controllers/gists_controller.rb
> +  before_action :require_admin, only: %i[index]
у нас был урок, как разделять экшены между админом и общей частью?

2022-04-16 18:05 UTC, DenisTDA commented on app/services/gist_question_service.rb
> +  end
объясни приемущества возвращать объект или структу вместо хеша. В коде рельсов очень часто используется хеш, но не признается плохим стилем.

2022-04-16 18:06 UTC, DenisTDA commented on app/services/gist_question_service.rb
> +    { gist: gist,
да, мое упущение. не доработал.

2022-04-16 18:14 UTC, DenisTDA commented on app/services/gist_question_service.rb
> +      url: gist.url,
нигде не сказано, что есть верная ссылка.

2022-04-16 18:15 UTC, DenisTDA commented on app/services/gist_question_service.rb
> +    gist.url.include?(API_ENDPOINT)
ранее ты сам писал, что в строке может быть что угодно. Как узнаем, что там вообще есть ссылка.

2022-04-17 08:27 UTC, DenisTDA commented on config/locales/en.yml
> +      success: "Gist was saved successful! The URL: %{url_gist}"
забавные мелочи, которые занимают полдня поиска решения... да и то не в явном виде.

2022-04-23 21:44 UTC, merged