feat: task14, add js-files, correct route for devise
DenisTDA/TestGuru pull request #18
Opened 2022-04-23 21:50 UTC by DenisTDA

2022-04-24 11:53 UTC, VidgarVii requested changes

2022-04-24 11:53 UTC, VidgarVii commented on app/assets/javascripts/utilities/checklogin.js
> +  var control = document.querySelector('.check-password')
Время глобальных var-ов прошло. при объявлении переменных используй let/const. Так безопасней и код становиться понятней. Обязательно по гугли отличие!

2022-04-24 11:53 UTC, VidgarVii commented on app/assets/javascripts/utilities/checklogin.js
> +  var fieldsInput = form.querySelectorAll('input')
при каждом изменении поля происходит поиск элементов. Эта операция очень дорогая и долгая. Выноси поиск элементов за пределы события

2022-04-24 11:53 UTC, VidgarVii commented on app/assets/javascripts/utilities/checklogin.js
> +}
лучше потренироваться в ООП. JS позволяет создавать классы и браузеры это понимают, пусть пока и без инкапсуляций, но уже хоть что-то.
По пробуй создать такой класс утилиту, который принимает html элемент. И далее пусть эта утилита работает только с этим элементов. Таким образом мы сможем пере использоваться утилиту сколько угодно раз с разными элементами без переписывания кода. И так вся логика функционала будет обёрнута в класс, а не просто болтаться где-то снаружи. 
http://old.code.mu/books/javascript/oop/

2022-04-24 11:53 UTC, VidgarVii commented on app/assets/javascripts/utilities/sorting.js
> +}
те же самые замечания

2022-04-24 11:53 UTC, VidgarVii commented on app/assets/javascripts/utilities/sorting.js
> +  console.log(rows[0])
отладочный код стоит убрать

2022-04-24 12:11 UTC, VidgarVii requested changes

2022-04-24 12:11 UTC, VidgarVii commented on app/assets/javascripts/utilities/checklogin.js
> +  var control = document.querySelector('.check-password')
вешаешь событие только на 1 поле user_password_confirmation
Если исправить пароль в user_password то скрипт не будет это учитывать. Получается не до работка

2022-04-29 16:19 UTC, VidgarVii requested changes

2022-04-29 16:19 UTC, VidgarVii commented on app/assets/javascripts/utilities/checklogin.js
> +  if(form) {new CheckPasswordConfirm(form)}
if (form) new CheckPasswordConfirm(form)

2022-04-29 16:19 UTC, VidgarVii commented on app/assets/javascripts/utilities/checklogin.js
> +  if(form) {new CheckPasswordConfirm(form)}
в этом файле лучше оставить только класс. А использование вынести в другой файл. Что бы не было бардака в коде.

2022-04-29 16:19 UTC, VidgarVii commented on app/assets/javascripts/utilities/checklogin.js
> +class CheckPasswordConfirm {
по соглашению название файла должно быть таким же как класс.

2022-04-29 16:19 UTC, VidgarVii commented on app/assets/javascripts/utilities/sorting.js
> +})
все те же самые замечания по файлу

2022-05-01 18:55 UTC, BubuntuClu requested changes

2022-05-01 18:55 UTC, BubuntuClu commented on app/assets/javascripts/utilities/CheckPasswordConfirm.js
> +    if (text1 === '' || text2 === '') {
какой-то сложный код получился.
у тебя по сути возможно 3 варианта.
1 - когда подтверждение пустое, тогда нужно убрать всякую отметку с полей
2 - когда пароли не совпадают, тогда надо повесить стили предупреждения
3 - когда пароли совпадают


if +return чтобы остановить выполнение дальнейших проверок при пустом подтверждении
и обычный if/else на проверку совпадений паролей

2022-05-02 05:51 UTC, DenisTDA commented on app/assets/javascripts/utilities/CheckPasswordConfirm.js
> +    if (text1 === '' || text2 === '') {
Павел в предшествующих замечаниях обратил внимание на то, что по заполнению поля confirmation и совпадению пароля, снова изменить поле password, то знак не измениться (а должен). Я просто усилил проверку, на предмет, если хоть одно поле пустое, то проверять нечего.

2022-05-02 05:54 UTC, DenisTDA commented on app/assets/javascripts/utilities/CheckPasswordConfirm.js
> +    if (text1 === '' || text2 === '') {
Проверка совпадения реализована как ты и описываешь. О главном: я не получил ответы на свои вопросы по поводу настройки webpacker.

2022-05-02 05:55 UTC, DenisTDA commented on app/assets/javascripts/utilities/CheckPasswordConfirm.js
> +    if (text1 === '' || text2 === '') {
Так и не понял, как правильно настроить webpaker? Получается так, что если убрать файлы из app/assets/javascripts/utilities и разместить их в app/javascript/packs, то файлы обрабатываются, но скрипт не работает. А если оставить в app/assets/javascripts/utilities и убрать из app/javascript/packs, то куча ошибок. Работает только  тогда, когда эти файлы сразу в обеих папках. Так не должно быть... Как правильно? Это то что я спрашивал у Паши.

2022-05-03 17:30 UTC, merged