Task18 2
DenisTDA/TestGuru pull request #22
Opened 2022-06-28 22:46 UTC by DenisTDA

2022-06-29 07:17 UTC, VidgarVii requested changes

2022-06-29 07:17 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    params[:test][:time_limit] =
для расчётов обычно используют минимально возможное значение. В данном случаи секунды. Так меньше шансов ошибиться и не надо на беке всё это кодировать в какой-то другой вид. Тем более надо каждый раз проверять дедлайн прохождения теста.

2022-06-29 07:17 UTC, VidgarVii commented on app/controllers/results_controller.rb
> +    redirect_to result_result_path(@result) if !@timer.time_limit.zero? && @timer.time_out?
у модели есть метод отвечающий завершён ли тест. Не стоит ли проверку времени положить туда?

2022-06-29 07:17 UTC, VidgarVii commented on app/helpers/tests_helper.rb
> +    { hours: hours.to_i, minutes: minutes.to_i, seconds: seconds.to_i, time_str: time_string }
не пришлось бы этим заниматься если бы в таблице лежали секунды
на фронте с помощью JS можно легко переводить секунды в минуты.

2022-06-29 07:17 UTC, VidgarVii commented on app/services/timer_test.rb
> +    Time.now
всегда надо учитывать часовой пояс

2022-06-29 07:17 UTC, VidgarVii commented on app/services/timer_test.rb
> +class TimerTest
лишний класс. Проверить время можно так. result.created_at сложить с  test.timer И сравнить с текущим временем. 1 строчка кода. И можно это проверить в модели Result. Так как он следит за завершением теста.

2022-06-29 07:17 UTC, VidgarVii commented on app/views/results/show.html.erb
> +<% if !@timer.time_limit.zero?%>
в таблице тип поле строка. А тут проверяется как число. Это очень запутывает и усложняет дебагинк

2022-06-29 07:17 UTC, VidgarVii commented on config/initializers/time_formats.rb
> +Time::DATE_FORMATS[:time_sec] = '%H:%M:%S'
не стоит переопределять константы

2022-06-29 07:17 UTC, VidgarVii commented on app/assets/javascripts/utilities/TimeProgressBar.js
> +      window.location.href = this.href
я бы скорее не локейшен менял, а засабмитил форму: `form.submit()`
такой вариант менее "хакерский", все идет в русле естественного сценария (сабмит формы > контроллер > модель > контроллер > вьюха)

как раз в модели можно со стороны сервера проверить не истек ли таймер и "завершить" тест (обнулифаить текущий вопрос)
контроллер в этом случае сделает редирект на `result` безо всяких `JS` смен локации

2022-06-30 09:00 UTC, DenisTDA commented on config/initializers/time_formats.rb
> +Time::DATE_FORMATS[:time_sec] = '%H:%M:%S'
Так я ее и не переопределил.. в документации написано, что можно добовлять свои форматы.

2022-06-30 09:03 UTC, DenisTDA commented on app/controllers/admin/tests_controller.rb
> +    params[:test][:time_limit] =
а разве у меня не так получилось?

2022-07-01 13:29 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    params[:test][:time_limit] =
я имею ввиду что достаточно передать 1 цифру. Секунды И не пришлось бы тут делать все эти вычисления

2022-07-01 13:29 UTC, VidgarVii commented on app/helpers/tests_helper.rb
> +    { hours: hours, min: minutes, sec: seconds }
Не стоит полагаться на объекты вне контекста или какое-то  глобальное состояние. Хелперу безопасно работать только с теми данными, которые приходят аргументами в метод

2022-07-01 15:38 UTC, DenisTDA commented on app/helpers/tests_helper.rb
> +    { hours: hours, min: minutes, sec: seconds }
ну да.. я об этом думал, но из каких то соображений решил сделать так. Поправлю.

2022-07-02 07:54 UTC, merged